# Основы pandas. Домашнее задание

Задание 1.
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
Определите какому фильму было выставлено больше всего оценок 5.0.

In [4]:
import pandas as pd
data = pd.read_csv('ratings.csv')

data_rating = data[ data[' rating'] == 5 ]
data_rating[' movie_id'].value_counts().head(1).reset_index()

   index   movie_id
0    318        523

Задание 2. По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) 
категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [3]:
import pandas as pd
data = pd.read_csv('power.csv')

filtered_countries = data[ (data['country']=='Latvia') | (data['country']=='Lithuania') | (data['country']=='Estonia')]
new_data = filtered_countries.sort_values(by=['year', 'category' ], ascending=[True, True])

a = new_data[ (new_data.year >= 2005) & (new_data.year <= 2010) & 
            ((new_data.category == 4) | (new_data.category == 12) | (new_data.category == 21)) & 
            (new_data.quantity >= 0)]

print('Суммарное потребление товаров странами Прибалтики (Латвия, Литва и Эстония) по годам и группам товаров \nпредставлено в таблице ниже. ')
a.groupby(['year','category'])['quantity'].sum().reset_index()

Суммарное потребление товаров странами Прибалтики (Латвия, Литва и Эстония) по годам и группам товаров
представлено в таблице ниже.

    year  category  quantity
0   2005         4      22.0
1   2005        12      18.0
2   2005        21   37124.0
3   2006         4      12.0
4   2006        12      18.0
5   2006        21   38700.0
6   2007         4       0.0
7   2007        12    2454.0
8   2007        21   39012.0
9   2008         4      12.0
10  2008        12    2029.0
11  2008        21   39536.0
12  2009         4       0.0
13  2009        12     862.0
14  2009        21   41920.0
15  2010         4       0.0
16  2010        12     945.0
17  2010        21   37916.0

Задание 3. Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [2]:
import pandas as pd
pd.read_html('https://www.finam.ru/quotes/indices')[0]

,Unnamed: 0,Инструмент,Посл. сделка,% Изм. цены,Открытие,Макс.,Мин.,Закрытие,"Объем, шт.",Время обн.
0,NaN,D&J-Ind*,22556.77,6.38%,21472.750,22599.660,21431.470,21204.870,NaN,26.03 23:20
1,NaN,Futsee-100*,5498.03,-5.46%,5815.730,5815.730,5497.930,5815.730,NaN,27.03 15:50
2,NaN,NASDAQ**,7797.54,0%,7462.210,7809.830,7462.210,7797.540,NaN,27.03 00:15
3,NaN,N225Jap*,19167.04,2.69%,19021.970,19366.290,18832.210,18664.600,NaN,27.03 08:59
4,NaN,Индекс РТС,968.96 ₽,-4.73%,1013.150,968.440,944.410,1017.030,717 335 402,27.03 15:50
5,NaN,Индекс МосБиржи 10,4221.91 ₽,-3.48%,4382.230,NaN,NaN,4374.030,37 662 919 616,27.03 15:50
6,NaN,Индекс МосБиржи,2414.58 ₽,-3.03%,2491.700,NaN,NaN,2489.970,56 311 618 138,27.03 15:50
7,NaN,SandP-500*,2630.07,6.24%,2501.290,2637.010,2500.720,2475.560,NaN,26.03 23:02
8,NaN,CSI300 (Китай),3710.061,0.32%,3746.391,3758.783,3709.921,3698.047,4 294 967 295,27.03 11:05
9,NaN,AMMEKS*,1550.35,2.25%,1529.930,1615.610,1525.380,1516.190,NaN,26.03 23:10
10,NaN,ASX200 (Австралия)*,4842.4,-5.3%,5113.300,5236.700,4842.400,5113.300,NaN,27.03 08:11
11,NaN,Bovespa (Бразилия),77709.66,3.67%,74956.050,78846.340,74923.270,74955.570,NaN,26.03 23:13
12,NaN,BSE Sensex (Индия),29815.59,-0.44%,30747.810,31126.030,29346.990,29946.770,NaN,27.03 13:00
13,NaN,CAC 40,4343.68,-4.4%,4433.950,4471.370,4329.990,4543.580,NaN,27.03 15:50
14,NaN,CSI200 (Китай),3939.505,-0.11%,3996.487,4000.255,3937.994,3943.812,4 294 967 295,27.03 10:00
15,NaN,Hang Seng (Гонконг),23372.43,0.09%,23768.410,23791.200,23354.010,23352.340,NaN,27.03 10:59
16,NaN,KOSPI (Корея),1717.73,1.87%,1756.070,1759.050,1668.210,1686.240,1 067 892,27.03 09:30
17,NaN,Merval (Аргентина),25953.06,-1.46%,25605.030,27769.180,25322.320,26338.030,NaN,26.03 23:29
18,NaN,MICEX LC,2264.3 ₽,1.89%,2222.370,NaN,NaN,2222.360,21 850 894 535,17.05.13 18:44
19,NaN,MICEX MC,2059.02 ₽,2.55%,2007.730,NaN,NaN,2007.860,3 250 535 185,17.05.13 18:44
20,NaN,MICEXCBIGP,94.87 ₽,0.07%,94.820,NaN,NaN,94.800,3 364 431 230,24.12.13 18:32
21,NaN,MICEXCBIGP3Y,94.54 ₽,0.07%,94.490,NaN,NaN,94.470,2 015 644 343,24.12.13 18:18
22,NaN,MICEXCBIGP5Y,112.6 ₽,0.07%,112.520,NaN,NaN,112.520,1 112 133 869,24.12.13 18:32
23,NaN,MICEXMBIGP,97.88 ₽,0.05%,97.830,NaN,NaN,97.830,1 565 270 792,24.12.13 17:38
24,NaN,MOEXREPO акц 12:30,5.9 ₽,4.8%,5.900,NaN,NaN,5.630,37 439 774 394,27.03 12:30
25,NaN,MOEXREPO акц 19:00,5.84 ₽,0%,0.000,NaN,NaN,5.840,NaN,27.03 00:00
26,NaN,MOEXREPO обл 12:30,5.88 ₽,4.07%,5.880,NaN,NaN,5.650,365 012 424 018,27.03 12:30
27,NaN,MOEXREPO обл 19:00,5.95 ₽,0%,0.000,NaN,NaN,5.950,NaN,27.03 00:00
28,NaN,MOEXREPO1W обл 12:30,5.64 ₽,-2.76%,5.640,NaN,NaN,5.800,36 720 828 545,27.03 12:30
29,NaN,MOEXREPO1W обл 19:00,5.97 ₽,0%,0.000,NaN,NaN,5.970,NaN,27.03 00:00